version: '3.8'

services:
  backend:
    build:
      context: ./country-api-middleware
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_STORAGE=/data/database.sqlite
      - SESSION_SECRET=${SESSION_SECRET}
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - database-data:/data

  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  database-data: